### ISSUE TITLE
Release Management Planning - Update README with links to wiki

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/ReleaseManagement#20]
**Problem description**

Hi guys, I may not find the release management planning. If we haven't got a planning yet, I'll suggest TSC as the leaders to set a overall release planning. And all code owners/maintainers follow. 

Release planning may contain:
1. **Milistones**. Usually M1 M2 M3 M4. For example, M1 is for new features planning. M2 is for new features freese. M3 is for coding freese. M4 is for signing. 
2. **One year can have 1~2 releases.**
3. In the very beginning of each release, we need to **decide the date** for M1 M2 M3 M4. And then code owners may follow.

**Comment by hdamker** [comment]
Hi @ShutingQing, the release process and planning is under discussion within the Release Management and the TSC already since several weeks. All the results are within the wiki (I will propose an update of the README here in the repository).

* Release Management within the CAMARA project wiki: https://wiki.camaraproject.org/display/CAM/Release+Management+Working+Group
* Current description of the Release Management process: https://wiki.camaraproject.org/display/CAM/CAMARA+Release+Process
* Timeline for the first "CAMARA Meta-Release" in Fall 2024: https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24 (the concrete instructions what the API Sub Projects have to provide for the Milestones is work in progress)

The TSC minutes are always a good place to get information such the above, see for example here: https://wiki.camaraproject.org/display/CAM/2024-04-04+TSC+Minutes
