### ISSUE TITLE
DeviceStatus r1.1 release review

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#57]
**Release PR or issue to review**

https://github.com/camaraproject/DeviceStatus/pull/190

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (wuth creation date of the release)

**Additional comments**

**Comment by hdamker** [comment]
Main review results (also noted within https://github.com/camaraproject/DeviceStatus/pull/190):
* YAML: x-camara-commonalities field need to be added
* CHANGELOG.md: change since last public release need to be added, currently the once from r0.6 (alpha API versions) are not incorporated
* Test files not yet included, "Will be provided for 0.6.0-rc.2" - ok, as exception defined by TSC for M3 in Fall24

**Comment by hdamker** [comment]
First repository release with multiple APIs 🎉 - congratulations!
